server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_microservice?createTableIfNotExists=true
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
                     # To register this microservice on Eureka client with following name
  application:
    name: USER-MICROSERVICE

                      # To make this microservice as a client & register with Eureka server
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

                     # Actuator configurations
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

                    # CircuitBreaker configuration
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 12
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      ratingHotelRetry:
        max attempts: 3
        wait-duration: 3s

  rate-limiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s