server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8081    # OR-> lb://USER-SERVICE
          predicates:
            - Path=/user/**              # for multiple controllers-> /user/**,/staff/**,/admin/**

        - id: HOTEL-SERVICE
          uri: http://localhost:8082    # OR-> lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**

        - id: RATING-SERVICE
          uri: http://localhost:8083    # OR-> lb://RATING-SERVICE
          predicates:
            - Path=/rating/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
